# Uncomment the next line to define a global platform for your project
platform :osx, '10.11'

target 'DMMacAnimation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DMMacAnimation
  pod 'Masonry', '~> 1.0.2'

end
